import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar/Navbar";
import Footer from "./component/footer/Footer";

export const metadata = {
  title: "Blog app",
  description: "Generated by Bloom It Solution",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="container">
          <div className="wrapper">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
